config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
  resources :manuals
  resources :pages
  root 'manuals#index'



  scope '/admin' do
    resources :users
    resources :categories
  end
end

end

app/models/manual.rb
# == Schema Information
#
# Table name: manuals
#
#  id          :integer          not null, primary key
#  title       :string
#  category_id :string
#  user_id     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Manual < ApplicationRecord
  validates :title, :category_id, presence: true

  has_many :pages, -> { order(position: :asc) }
  belongs_to :category
  belongs_to :user
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  before_action :set_manual, only: %i[show edit update destroy]
  respond_to :html

  def index
    if params[:set_locale]
      redirect_to manuals_path(locale: params[:set_locale])
    else
      @manuals = Manual.all
      respond_with(@manuals)
    end
  end

  def show
    @manual = Manual.includes(pages: :blocks).find(params[:id])
    respond_with(@manual)
  end

  def new
    @manual = Manual.new
    @categories = Category.order(:title)
    respond_with(@manual)
  end

  def edit
    @categories = Category.order(:title)
  end

  def create
    @manual = current_user.manuals.create(manual_params)
    @manual.save
    respond_with(@manual)
  end

  def update
    @manual.update(manual_params)
    respond_with(@manual)
  end

  def destroy
    @manual.destroy
    respond_with(@manual)
  end

  private

  def set_manual
    @manual = Manual.find(params[:id])
  end

  def manual_params
    params.require(:manual).permit(:title, :category_id, :user_id)
  end
end

app/helpers/manuals_helper.rb
module ManualsHelper
  def manual_data(manual)
    { manual_id: manual.id, pages: manual.pages, current_page: 0, edit_mode: false }
  end






end

app/views/manuals/_form.html.erb
<h3><%= title %></h3>
<%= form_with(model: manual, local: true) do |form| %>
  <% if manual.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% manual.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :manual_title %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select :category_id, @categories, :id, :title, include_blank: t('view.manual.select_category') %>
  </div>

  <%= form.submit t('action.save'), class: "btn btn-primary" %>
  <%= link_to t('action.back'), manuals_path, class: "btn btn-secondary" %>
<% end %>

app/views/manuals/edit.html.erb
<%= render 'form', manual: @manual, title: t('title.manual.edit') %>

app/views/manuals/index.html.erb
<h3><%= Manual.model_name.human(count: 2) %></h3>

<table class="table table-striped table-bordered table-sm">
  <thead>
    <tr class="row">
      <th class="col-2"><%= Manual.human_attribute_name("title") %></th>
      <th class="col-2"><%= Manual.human_attribute_name("category") %></th>
      <th class="col-2"><%= Manual.human_attribute_name("author") %></th>
      <th class="col-6"><%= t('action.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @manuals.each do |manual| %>
      <tr class="row">
        <td class="col-2"><%= manual.title %></td>
        <td class="col-2"><%= manual.category.title %></td>
        <td class="col-2"><%= manual.user %></td>

        <td class="col-6">
          <%= link_to t('action.show'), manual, class: 'btn btn-sm btn-secondary' %>
          <% if user_signed_in? %>
          <%= link_to t('action.edit'), edit_manual_path(manual), class: 'btn btn-sm btn-secondary' %>
          <%= link_to t('action.destroy'), manual, class: 'btn btn-sm btn-secondary', method: :delete,
                                                                          data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if user_signed_in? %>
<%= link_to t('action.manual.new'), new_manual_path, class: "btn btn-primary" %>
<% end %>

app/views/manuals/new.html.erb
<%= render 'form', manual: @manual, title: t('title.manual.new') %>

app/views/manuals/show.html.erb
<h2 class="manual_title"><%= @manual.title %></h2>

<%= content_tag :div, nil, id: "manual", data: {'initial-state' => manual_data(@manual)} %>

<div class="manual_details">
  <p>
    <strong><%= Manual.human_attribute_name("category") %>:</strong>
    <%= @manual.category.title %>
    <br>
    <strong><%= Manual.human_attribute_name("author") %>:</strong>
    <%= @manual.user %>
    <br>
    <strong><%= Manual.human_attribute_name("created_at") %>:</strong>
    <%= @manual.created_at.to_date%>
    <br>
    <strong><%= Manual.human_attribute_name("updated_at") %>:</strong>
    <%= @manual.updated_at.to_time%>
  </p>
</div>