config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)' do
  resources :manuals
  resources :pages
  root 'manuals#index'



  scope '/admin' do
    resources :users
    resources :categories
  end
end

end

app/views/layouts/_alert.html.erb
<% if message.present? %>
  <div class="alert alert-<%= type %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<%= render 'layouts/alert', type: 'success', message: notice %>
<%= render 'layouts/alert', type: 'danger', message: alert %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to t('view.manuals'), manuals_path, class: 'nav-link' %>
    </li>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="<%= t('view.search') %>">
      </form>

      <li class="nav-item">
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <%= t('view.langueges') %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to "Russian",locale: 'ru' %></li>
            <li><%= link_to "English",locale: 'en' %></li>
          </ul>
        </div>
      </li>
      <% if can? :manage, User %>
        <li class="nav-item">
          <%= link_to t('view.users'), users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('view.categories'), categories_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span><%= current_user.to_s %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to t('action.devise.edit_profile'), edit_user_registration_path, class: 'dropdown-item' %>
          <%= link_to t('action.devise.log_out'), destroy_user_session_path, :method => :delete, class: 'dropdown-item' %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to t('action.devise.log_in'), new_user_session_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Can you?</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>
    
    <div class='container' id="root">
      <%= yield %>
    </div>
    

  </body>
</html>